### ISSUE TITLE
Through Hydra Cli rest, we can see its load balancing and sending requests to running instances. But in typical web application to call hydra services, how can i configure to call with domain we specify without port?

### ISSUE THREAD

**Issue by chandru-kumar** [pnxtech/hydra-express#124]
Through Hydra Cli rest, we can see its load balancing and sending requests to running instances. But in typical web application to call hydra services, how can i configure to call with domain we specify without port?

**Comment by cjus** [comment]
@ChandrewR Let us know whether the existing documentation is unclear.  We'll be happy to improve it.

https://www.hydramicroservice.com/docs/hydra-core/messaging.html

**Comment by chandru-kumar** [comment]
Hi Carlos, Thanks for the reply..But what I am looking is how to call load balanced microservices in hydra. For example, i have a microservice runnning on two instances - http//ipaddress:7000/api and http//ipaddress:7001/api. I need to add domain and configure these two instances to 80 port to call as http//myservicename/api in Angular app without mentioning port - http//ipaddress:7000/api ..So it will get load balanced..Can you help me on this please? I dont see any docs for this..

**Comment by cjus** [comment]
I see. You could use something like NGinX.  However, we use HydraRouter for this purpose.
https://www.hydramicroservice.com/docs/tools/hydra-router/

**Comment by chandru-kumar** [comment]
![Hydra-config](https://user-images.githubusercontent.com/26222838/54866526-e2fc5200-4d9a-11e9-87a6-db1c14ea0fa0.PNG)

![Hydra-service](https://user-images.githubusercontent.com/26222838/54866560-51d9ab00-4d9b-11e9-8576-640eb01b03bc.PNG)
![Hydra-routes](https://user-images.githubusercontent.com/26222838/54866561-51d9ab00-4d9b-11e9-9d00-32346fb4f050.PNG)


I have tried adding externalRoutes and didn't work..I made it as http as well and called the api as http://test-service.com/processfileapis/v1/getfilestatus and it didn't work. In doc, I'm seeing [get]/.... and is it mandatory to mention request type?

**Comment by chandru-kumar** [comment]
Not sure about this externalRoutes comes with Hydra-route(or i should implement NGinX and then use this approach) and how to use it to load balance? I couldn't see any sample project in Git Repo as well.. Can you please help sharing any examples, if you have?

**Comment by cjus** [comment]
@ChandrewR Hydra services can communicate with *each other* using internal load balancing which doesn't require a port.  You can do that using hydra.sendMessage and hydra.makeAPIRequest.  However, if you're sending a message from outside of hydra, as with an incoming web API request from a client on the Internet, then you'll need a tool which can route to one of several hydra enabled services.  

NGinx and other load balancers have this support, as does Hydra-Router.  This is more easily done when the hydra-services are running on different machines with their own IP addresses. That way the port address is the same for each service instance of the the same type.

Another popular way of handling all this is to use a Docker Swarm or Kubernetes cluster which has internal support for load balancing requests to containers.

All of this is more of a networking issue rather than a Hydra specific issue, as Hydra has support so that it works in all of the above situations.

I notice based on your posts times that we may be in compatible timezones.  Let me know if you'd like me to setup a zoom conference call to we can speak about the above. I've love to see you up and running. If you'd like to do that send me an email to cjus34@gmail.com so we can setup a time.  We'll then posts our findings here for future visitors.

**Comment by chandru-kumar** [comment]
Thank you Carlos. I will try setup with Nginx for load balancing and post the updates here..If I'm unable to make it, will send you an email to pitch in conference call. Tons of thanks for your time and answers so far.

**Comment by chandru-kumar** [comment]
Hi Carlos - I'm done. Its up and running with load balanced with NGINX setup..Thank you!!
